### ISSUE TITLE
Issue with Persona REST API

### ISSUE THREAD

**Issue by sujitsagar** [IndicoDataSolutions/IndicoIo-python#183]
I am using REST API with Python

Here is my code
`json.loads( urlfetch.fetch( url='http://apiv2.indico.io/personality?key=<<KEY>>', 
                        payload=urllib.urlencode({'data': str(text), 'persona' : 'true', 'top_n' : 1 }),
                        method=urlfetch.POST,
                        headers={'Content-Type': 'application/json'} ).content )`

And the response is 
`{u'error': u'Provided argument for `persona` keyword was not of type `boolean`'}`

Can you suggest a way to pass persona in Payload?

**Comment by sihrc** [comment]
Perhaps, passing it in as a boolean instead of a string as the error suggests.
`json.loads( urlfetch.fetch( url='http://apiv2.indico.io/personality?key=<<KEY>>', payload=urllib.urlencode({'data': str(text), 'persona' : True, 'top_n' : 1 }), method=urlfetch.POST, headers={'Content-Type': 'application/json'} ).content )`

Also, passing in the API key as a url parameter will soon be deprecated. Please pass it in the header under the field X-ApiKey or as part of the payload as api_key.

**Comment by sihrc** [comment]
As this is not an issue with our client library itself, I am closing this issue.
