### ISSUE TITLE
More complete setup.py file

### ISSUE THREAD

**Issue by madisonmay** [IndicoDataSolutions/IndicoIo-python#20]
I think we need to ensure scipy is installed as well to avoid issues with the skimage install.  Alternatively we could move to an image resize operation that doesn't rely on skimage, as that's a rather large dependency that serves a rather small purpose.

**Comment by Slater-Victoroff** [comment]
I looked into this and it looks like PIL/skimage really is the way to resize images if we want to do it well. We could write a small function for scaling, but the skimage resize is actually a non-trivial operation that would probably take a couple days of development to reproduce in a more lightweight container.

It might be worth it, but correct me if I'm wrong, this functionality isn't present in any other package, and the best way of using this is really via URL (not that that's possible yet). I feel like it might be a better solution to integrate a really simple ability to push some local file to an online image hosting provider like imgur, and only accept images through the API that are already resized on the client side.

I feel like this actually significantly improves the user experience overall, since it will stop people from accidentally sending post requests with really large images, resulting in really long turnaround times for very little reason. Additionally it lets us maintain a much thinner client with uniform cross-language functionality.

Will wait for your thoughts, but I'm going to start investigating this solution.

**Comment by madisonmay** [comment]
https://github.com/IndicoDataSolutions/IndicoIo-python/issues/21

We'll likely need scipy for other reasons anyhow, so I ended that line of reasoning.

**Comment by madisonmay** [comment]
The `setup.py` file issue was resolved a while back, and the other issues mentioned in this thread have either been resolved or are documented in separate issues. Closing...
